### ISSUE TITLE
Inconsistent exceptions

### ISSUE THREAD

**Issue by dnephin** [Yelp/swagger-py#100]
We've observed that the `SynchronousHttpClient` and `AsynchronousHttpClient` raise different exceptions  (`requests.exceptions.HTTPError` vs `swaggerpy.exception.HTTPError`).

We need to ensure that all exceptions at least have the same base class, regardless of client implementation.

We may be able to wait for sprockets, but we should still address this.

**Comment by prat0318** [comment]
need to fix it in bravado as well.
