### ISSUE TITLE
handle_response_errors swallows stacktrace

### ISSUE THREAD

**Issue by laucia** [Yelp/swagger-py#108]
```/swaggerpy/response.py#handle_response_errors``` is not preserving the stacktrace when reraising the errors, making debugging difficult. 

Moving to the 3 parameters version of raise would solve this :

```
if hasattr(e, 'response') and hasattr(e.response, 'text'):
        ....

exc_info = sys.exc_info()
raise sys.exc_info[0], e.args, sys.exc_info[2]
```

**Comment by bpicolo** [comment]
whoever fixes this, make sure to avoid the sys.exc_info memory leak

**Comment by prat0318** [comment]
@bpicolo from what i read, storing exc_info into a local variable can lead to the memory leak issue. lmk if #137 looks good.
