### ISSUE TITLE
Error with list handling in latest version

### ISSUE THREAD

**Issue by heath90** [Yelp/swagger-py#109]
Currently we use swagger-py to make a call with params like the following:

```python
param = {
            'q': prefix.encode('utf-8'),
            'recent_locations': [location.encode('utf-8')
                                 for location in recent_locations],
        }
```

where each location is a string like "San Francisco, CA"

On the service side we get the recent_locations with the following:

```python
recent_locations = request.params.getall('recent_locations')
```

Also note that our api docs for this parameter look like:

```
{
    "name": "recent_locations",
    "description": "recent locations from RECENT_LOCATIONS cookie",
    "type": "string",
    "paramType": "query",
    "required": false
},
```

This has worked fine for us up to version 0.7.2. However, after bumping to 0.7.3+ we get an error whenever the service endpoint is called with a message:

"dictionary update sequence element #0 has length 16; 2 is required"

This must have been caused by how swagger-py handles / encodes lists changing between 0.7.2 and 0.7.3 or 0.7.4

See https://jira.yelpcorp.com/browse/SUGGEST-284 for more context and a full stack trace.

**Comment by dnephin** [comment]
We tracked this down to https://github.com/Yelp/yelp_uri/issues/13.  Once that is fixed, we can set a minimum version requirement for `yelp_uri` should  should resolve the issue.
