### ISSUE TITLE
Remove the model attributes if they are not required and not present in the response

### ISSUE THREAD

**Issue by prat0318** [Yelp/swagger-py#133]
Instead of providing a default value, remove the model field if not present in the response.

Changes should be around [here](https://github.com/Yelp/swagger-py/blob/8b8cadb81494dec71a4896cb287382d690430b74/swaggerpy/swagger_model.py#L360)

**Comment by bwbaugh** [comment]
Remove the attribute, or set it to `None`?

**Comment by prat0318** [comment]
I was thinking `None` would lead to ambiguity whether server sent a `null` or swaggerpy did it. But it turns out that there is no way in swagger spec 1.2 to refer to a `null` field, hence server can never send `null` as a field. Thus, changing field to `None` is also an equally valid option. A plus side of adding field with `None` is that it would avoid missing attribute error on the client side.

**Comment by changsi** [comment]
I am in favor of adding a None field value if it is missing. Just as what you said it avoid missing attribute error on the client side.
