### ISSUE TITLE
_request_options should be available for api-docs request

### ISSUE THREAD

**Issue by bpicolo** [Yelp/swagger-py#71]
Need to be able to pass similar _request_options to api docs requests

**Comment by dnephin** [comment]
This support is in #94

**Comment by bwbaugh** [comment]
@dnephin We're seeing the following deprecation warning:

```python
site-packages/swaggerpy/swagger_model.py:216: DeprecationWarning: Unlimited timeouts are deprecated.
  api['api_declaration'] = eventual.wait().json()
```

Sounds like that pull request might fix that since we'd be able to specify a timeout for retrieving the api-docs?

**Comment by dnephin** [comment]
hmm, probably not. I think we need to specify a timeout to `wait()`

**Comment by dnephin** [comment]
I've added support for a timeout param to the `request_options` , and set a default of 5s, which should remove that deprecation warning.

**Comment by bwbaugh** [comment]
:heart: thanks!
