### ISSUE TITLE
Improve swaggerpy performance

### ISSUE THREAD

**Issue by dnephin** [Yelp/swagger-py#87]
We're seeing that building the client for large APIs (~30 api docs) can be very slow (900ms!).  This ticket is to track some possible improvements.

From the profile:
 1. making requests for documents is ~700ms. We should do these async and all at once
 2. `create_model_docstring()` is 15ms, which is significant, and is only going to be used in very rare situations. It would be great to find a way to avoid this time, maybe with an optional parameter to enable them?

**Comment by dnephin** [comment]
@prat0318 what do you thing about the second point?  

We could pass in a parameter, but it's pretty deep in the callstack so we'd have to pass it around a lot.  When do you see this docstring being used?

Since the models don't exist in code, they wouldn't be used by developers. It's possible that it could be used to document the class using sphinxdoc, but I would think that the swagger docs would be a better option.

Could we remove the model docstrings entirely?

I'm seeing them take around 8% of the time for some larger api docs.

**Comment by prat0318** [comment]
I was instead thinking to make the `create_model_docstring` **lazy** instead of optional or removal. It can be used to show api-docs model information when working on REPL. Like so,
```
In [12]: p = swagger_client.pet.models.Pet
In [13]: p?
Attributes:

category (Category)
status (str) : pet status in the store
name (str)
tags (list(Tag))
photoUrls (list(str))
id (long) : unique identifier for the pet
```
My proposed patch prat0318@454b8d6 (inspired by [SO post](http://stackoverflow.com/a/5191224/987896) ) now loads model docstring lazily.

Earlier (added a print statement inside `create_model_docstring`):
```
In [2]: swagger_client = client.get_client(
   ...:     "http://petstore.swagger.wordnik.com/api/api-docs")

create_model_docstring called!
create_model_docstring called!
create_model_docstring called!
create_model_docstring called!
create_model_docstring called!
```

With the patch:
```
In [2]: swagger_client = client.get_client(
   ...:     "http://petstore.swagger.wordnik.com/api/api-docs")
In [12]: p = swagger_client.pet.models.Pet

In [13]: p?
create_model_docstring called!
Type:            type
String form:     <class 'swaggerpy.swagger_model.Pet'>
File:            /Users/prat0318/projects/swagger-py/swaggerpy/swagger_model.py
Init definition: p(self, **kwargs)
Docstring:
Attributes:
...
```
The patch is crude though, would need some refactoring.

**Comment by dnephin** [comment]
Cool, making it lazy is a good idea. I wasn't sure if that was possible, but a classproperty makes sense.

**Comment by prat0318** [comment]
Also, i was wondering if improving the 'api-docs' computation is worth the effort as it will be invoked just once in 300 seconds. But if that is the case, we can get a lot of perf improvement by making the caching more smarter. After 300 seconds, api-docs call can be made to the server and the SHA of the response body can be compared to the earlier SHA and the earlier built cache can still be used if the SHA maches. This way validation and docstring part is executed only when `api-docs` are changed (which should happen rarely).

**Comment by dnephin** [comment]
I think if we were going with that approach we should be using the standard HTTP headers for caching. That way we could avoid all the download as well. The server would let us know if anything has changed.

I'm actually thinking that maybe the caching isn't necessary at all.  A client isn't really going to be able to take advantage of new fields or calls added to the swagger spec without making code changes (and fields should never be removed).

In what case would reloading the spec actually be beneficial?

**Comment by prat0318** [comment]
Reloading the spec is mainly intended to make it in sync with the actual response. Suppose on the server end, both spec and response change to return "id" as an integer instead of string. With caching the swagger response validation will fail max up to 300s. This is when, suppose, client can handle both string and integer for "id" via duck type (without any code change). This is not the best use-case for re-fetching, but something i can think of right now.

```
I think if we were going with that approach we should be using the standard HTTP headers for caching. That way we could avoid all the download as well.
```
That would need us to enforce a requirement on server side (by sending an extra parameter in HTTP header)?

**Comment by dnephin** [comment]
> Suppose on the server end, both spec and response change to return "id" as an integer instead of string.

This should never happen. API changes need to be backwards compatible. Changing a type is not backwards compatible, so in order to make that change the API should either change it's version or create a new endpoint.  

> That would need us to enforce a requirement on server side

Yup, it would require the server to send the correct header.

**Comment by prat0318** [comment]
IIRC even finding a new field in response which was not mentioned in the spec throws up swagger validation error. So that will be an issue.

**Comment by dnephin** [comment]
Hmm, that is unfortunate. We should relax that. We don't want every API call to fail for 300s every time we add a new field to a spec.

**Comment by prat0318** [comment]
I agree on that. I am not totally sure if currently, extra fields result in validation failure. We can track that in a separate issue, if that is the case.

**Comment by dnephin** [comment]
This was done in #89 and #90
